version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: react-app

  backend:
    build: ./backend
    container_name: node-api

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
